version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: sonar-bot
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sonar-bot-db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data